# Generated by Django 5.1 on 2024-11-18 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancha', '0002_tipousuario_remove_infraestructura_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infraestructura',
            old_name='horarios',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='infraestructura',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo'), ('reparacion', 'En Reparación')], default='activo', max_length=20),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('infraestructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='cancha.infraestructura')),
            ],
            options={
                'db_table': 'horario',
                'unique_together': {('infraestructura', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
